### PR TITLE
Fix views not being updated for the same answer formats

### LINKED ISSUE #13: First question textChoices repeating for every question when answerFormat:  SingleChoiceAnswerFormat has been added for multiple steps
I have added the question to survey kit in below format.
```

   steps.add(InstructionStep(
      title: 'Welcome to Lab Survey',
      text: 'Get ready for a bunch of questions!',
      buttonText: 'Let\'s go!',
    ));
    steps.add(
      QuestionStep(
        title: 'Done?',
        text: 'We are done, do you mind to tell us more about yourself?',
        answerFormat: SingleChoiceAnswerFormat(
          textChoices: [
            TextChoice(text: 'Yes', value: 'Yes'),
            TextChoice(text: 'No', value: 'No'),
          ],
        ),
      ),
    );
    steps.add(
      QuestionStep(
        title: 'Done?',
        text: 'kjdsfkjaskdfj?',
        answerFormat: SingleChoiceAnswerFormat(
          textChoices: [
            TextChoice(text: 'none', value: 'none'),
            TextChoice(text: 'none', value: 'noe'),
          ],
        ),
      ),
    );

```

and returning the task to suveyKit task,

```
 var task = NavigableTask(id: TaskIdentifier(), steps: steps);
 return task;
```
Issue is on pressing next, the question changes but options remain the same.

### PR DESCRIPTION
**Pull request by zeshuaro**
- For each of the view type, only the first one is rendered with the correct options/details
  - E.g. when using two `QuestionStep` and both set with `SingleChoiceAnswerFormat`, the second `QuestionStep` does not render the second `textChoices` but instead it renders the first ones
- This PR fixes this behaviour by adding a widget key to the view widget
  - The widget key is created using `StepIdentifier.id`
  - Fixes #13

### CODE REVIEW

File: lib/src/steps/identifier/identifier.dart [hunk 1]
```diff
@@ -1,13 +1,7 @@
...
+  final String id;
 
-  Identifier({String? id}) {
-    if (id == null) {
-      id = Uuid().v4();
-      return;
-    }
-    this.id = id;
-  }
+  Identifier({String? id}) : id = id ?? Uuid().v4();
```
Comment (zeshuaro) [inline lib/src/steps/identifier/identifier.dart:6]: This syntax avoids declaring the variable with `late`

File: lib/src/steps/step.dart [hunk 2]
```diff
@@ -3,18 +3,12 @@ import 'package:survey_kit/src/result/question_result.dart';
...
-  Step(
-      {StepIdentifier? id, this.isOptional = false, this.buttonText = 'Next'}) {
-    if (id == null) {
-      this.id = StepIdentifier();
-      return;
-    }
-    this.id = id;
-  }
+  Step({StepIdentifier? id, this.isOptional = false, this.buttonText = 'Next'})
+      : id = id ?? StepIdentifier();
```
Comment (zeshuaro) [inline lib/src/steps/step.dart:11]: This syntax avoids declaring the variable with `late`

**Review by Numoy — APPROVED** [review]
